grandnode/Plugins/Grand.Plugin.Payments.PayInStore/Models/ConfigurationModel.cs
using Grand.Framework;
using Grand.Framework.Mvc;
using Grand.Framework.Mvc.ModelBinding;
using Grand.Framework.Mvc.Models;

namespace Grand.Plugin.Payments.PayInStore.Models
{
    public class ConfigurationModel : BaseGrandModel
    {        
        [GrandResourceDisplayName("Plugins.Payment.PayInStore.DescriptionText")]
        public string DescriptionText { get; set; }

        [GrandResourceDisplayName("Plugins.Payment.PayInStore.AdditionalFee")]
        public decimal AdditionalFee { get; set; }

        [GrandResourceDisplayName("Plugins.Payment.PayInStore.AdditionalFeePercentage")]
        public bool AdditionalFeePercentage { get; set; }
    }
}

grandnode/Plugins/Grand.Plugin.Payments.PayInStore/Models/PaymentInfoModel.cs
using Grand.Framework.Mvc;
using Grand.Framework.Mvc.Models;

namespace Grand.Plugin.Payments.PayInStore.Models
{
    public class PaymentInfoModel : BaseGrandModel
    {
        public string DescriptionText { get; set; }
    }
}

grandnode/Plugins/Grand.Plugin.Payments.PayInStore/Controllers/PaymentPayInStoreController.cs
using Grand.Plugin.Payments.PayInStore.Models;
using Grand.Services.Configuration;
using Grand.Framework.Controllers;
using Grand.Framework.Mvc.Filters;
using Microsoft.AspNetCore.Mvc;
using Grand.Services.Localization;
using System.Threading.Tasks;
using Grand.Framework.Security.Authorization;
using Grand.Services.Security;

namespace Grand.Plugin.Payments.PayInStore.Controllers
{
    [AuthorizeAdmin]
    [Area("Admin")]
    [PermissionAuthorize(PermissionSystemName.PaymentMethods)]
    public class PaymentPayInStoreController : BasePaymentController
    {
        private readonly ISettingService _settingService;
        private readonly PayInStorePaymentSettings _payInStorePaymentSettings;
        private readonly ILocalizationService _localizationService;

        public PaymentPayInStoreController(ISettingService settingService, PayInStorePaymentSettings payInStorePaymentSettings, ILocalizationService localizationService)
        {
            _settingService = settingService;
            _payInStorePaymentSettings = payInStorePaymentSettings;
            _localizationService = localizationService;
        }

        public IActionResult Configure()
        {
            var model = new ConfigurationModel();
            model.DescriptionText = _payInStorePaymentSettings.DescriptionText;
            model.AdditionalFee = _payInStorePaymentSettings.AdditionalFee;
            model.AdditionalFeePercentage = _payInStorePaymentSettings.AdditionalFeePercentage;

            return View("~/Plugins/Payments.PayInStore/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!ModelState.IsValid)
                return Configure();
                
            //save settings
            _payInStorePaymentSettings.DescriptionText = model.DescriptionText;
            _payInStorePaymentSettings.AdditionalFee = model.AdditionalFee;
            _payInStorePaymentSettings.AdditionalFeePercentage = model.AdditionalFeePercentage;
            await _settingService.SaveSetting(_payInStorePaymentSettings);

            SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }
    }
}

grandnode/Plugins/Grand.Plugin.Payments.PayInStore/Views/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
}
@model Grand.Plugin.Payments.PayInStore.Models.ConfigurationModel
@using Grand.Framework;
<form asp-controller="PaymentPayInStore" asp-action="Configure" method="post">
    
    <div class="form-horizontal">
        <div class="form-body">
            <div class="form-group">
                <div class="col-md-3 col-sm-3 text-right">
                    <admin-label asp-for="DescriptionText" class="control-label" />
                </div>
                <div class="col-md-9 col-sm-9">
                    <admin-textarea asp-for="DescriptionText"></admin-textarea>
                    <span asp-validation-for="DescriptionText"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3 col-sm-3 text-right">
                    <admin-label asp-for="AdditionalFee" class="control-label" />
                </div>
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="AdditionalFee" />
                    <span asp-validation-for="AdditionalFee"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3 col-sm-3 text-right">
                    <admin-label asp-for="AdditionalFeePercentage" class="control-label" />
                </div>
                <div class="col-md-9 col-sm-9">
                    <label class="mt-checkbox mt-checkbox-outline control control-checkbox">
                        <admin-input asp-for="AdditionalFeePercentage" />
                         <div class="control__indicator"></div>
                    </label>
                    <span asp-validation-for="AdditionalFeePercentage"></span>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <div class="row">
                <div class="col-md-offset-3 col-sm-offset-3 col-md-9 col-sm-9">
                    <input type="submit" name="save" class="btn green" value="@T("Admin.Common.Save")" />
                </div>
            </div>
        </div>
    </div>
</form>

grandnode/Plugins/Grand.Plugin.Payments.PayInStore/Views/PaymentInfo.cshtml
<!DOCTYPE html>

<html>
<head>
</head>
<body>
    <iframe src="https://vpos.infonet.com.py:8888"
            width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="">
    </iframe>
    </body>
</html>
<script type="application/javascript">
    styles = {
    "form-background-color": "#001b60",
    "button-background-color": "#4faed1",
    "button-text-color": "#fcfcfc",
    "button-border-color": "#dddddd",
    "input-background-color": "#fcfcfc",
    "input-text-color": "#111111",
    "input-placeholder-color": "#111111"
    };
    window. onload = function () {
    Bancard.Checkout. createForm ('iframe-container', 'WR-YY9JmxsEZV3hpVGA7', styles);
    };
</script>